# Generated by Django 4.2.4 on 2023-08-31 13:40

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactus",
            name="message",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
