# Generated by Django 4.2.4 on 2023-09-01 12:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("careers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="featured_image",
            field=cloudinary.models.CloudinaryField(
                default="", max_length=255, verbose_name="Job Posting Graphic"
            ),
        ),
    ]
