# Generated by Django 4.2.4 on 2023-09-04 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("careers", "0002_jobposting_featured_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobposting",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Job Post",
                "verbose_name_plural": "Job Posts",
            },
        ),
    ]
