# Generated by Django 4.2.4 on 2023-09-01 12:11

import ckeditor_uploader.fields
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("press_release", "Press Release"),
                            ("policy_brief", "Policy Brief"),
                            ("blog_post", "Blog Post"),
                            ("annual_report", "Annual Report"),
                            ("financial_report", "Financial Report"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("content", ckeditor_uploader.fields.RichTextUploadingField()),
                ("summary", ckeditor_uploader.fields.RichTextUploadingField()),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "featured_image",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="Content Featured Image"
                    ),
                ),
                (
                    "featured_document",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="Reports"
                    ),
                ),
                ("audit_date", models.DateTimeField(blank=True, null=True)),
                ("published", models.DateTimeField()),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
