# Generated by Django 4.2.4 on 2023-09-06 02:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_alter_content_featured_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='featured_document',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='PDF Report'),
        ),
    ]
