# Generated by Django 4.2.4 on 2023-09-28 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_alter_content_featured_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['-published']},
        ),
    ]
