# Generated by Django 4.2.4 on 2023-09-28 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteeringapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'Volunteering Application', 'verbose_name_plural': 'Volunteering Applications'},
        ),
    ]
